### ISSUE TITLE
Make sure writes are thread safe

### ISSUE THREAD

**Issue by smellsblue** [bundler/gemstash#42]
We are using `Puma` in a threaded environment. `SQLite` gest unhappy if you try to commit from 2 threads. Do we need a monitor around write uses, or does `Sequel` have a way of handling this natively? Do we need to reduce the DB connection pool to 1 when using `SQLite`?

**Comment by pcarranza** [comment]
Reducing the pool to 1 is a good way of ensuring that we will not have race
conditions, but it will also generate a lot of contention.
What about this? https://www.sqlite.org/sharedcache.html

**Comment by indirect** [comment]
Create a separate connection for writes, use a `Monitor` around any code that uses it. This pattern already exists in the `bundler-api` codebase. :+1:

**Comment by segiddins** [comment]
Isn't this exactly what database transactions exist for?

**Comment by fotanus** [comment]
I suggest balancing the benefits of having more than one connection on the pool but having to use a monitor or any other kind of synchronization around it. I'm afraid that synchronizing that will hurt more than help. Synchronization is done with system calls, after all.

Maybe it is better to use only one connection and touch it only if we start suffering from that?

**Comment by pcarranza** [comment]
@segiddins Exactly. 

Should we run some tests before changing the code? I think that this threading issue should be handled by the database layer, maybe we need to tweak things a bit, but I rather not have specific SQLite cases hidden in the code.

Why don't we pull, say, 10,000 gems from actual rubygems and build the import script to inject them all at once and see how gemstash behaves and if it is still functional?

Still, this 10,000 gems case seems quite an isolated edge case as I don't expect people from doing this every day.

**Comment by smellsblue** [comment]
OK, so I would think transactions would solve this problem, except I use transactions whenever I'm dealing with a thread sensitive multi-statement database interaction, and yet I got this error in a project I work on:
```
E, [2015-10-17T09:15:31.970378 #12401] ERROR -- : Error while [REDACTED]: (ActiveRecord::StatementInvalid) SQLite3::BusyException: database is locked: [REDACTED SQL UPDATE]
  ~/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.10/lib/sqlite3/statement.rb:108:in `step'
  ~/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.10/lib/sqlite3/statement.rb:108:in `block in each'
  ...
  ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
  ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
  ...
```

I created a test script to replicate this using `Sequel` (like we use in Gemstash) rather than `ActiveRecord` and `Rails` from my project:

```ruby
# Gemfile
source "https://rubygems.org"
gem "sequel"
gem "sqlite3"

# migrations/01_create_tmp_table.rb
Sequel.migration do
  change do
    create_table :tests do
      primary_key :id
      String :value, size: 255, null: false
    end
  end
end

# threading.rb
#!/usr/bin/env ruby
require "sequel"
db_path = File.expand_path("../test.db", __FILE__)
db = Sequel.connect("sqlite://#{db_path}")
Sequel.extension :migration
Sequel::Migrator.run(db, File.expand_path("../migrations", __FILE__), use_transactions: true)

100.times do
  threads = []

  100.times do |i|
    threads << Thread.new do
      db.transaction do
        db[:tests].insert(value: "Value: #{i}")
        db[:tests].insert(value: "Value: #{i}")
      end
    end
  end

  threads.each &:join
end
```

At first nothing happened (I had slightly different values for how many times to insert etc), and I thought maybe I misunderstood my original problem. Then, after running it a bunch (maybe this problem only occurs once you have a certain size of dataset), I got this:
```
$ ./threading.rb
~/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `step': SQLite3::BusyException: database is locked (Sequel::DatabaseError)
	from ~/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `block in each'
	from ~/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `loop'
	from ~/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `each'
	from ~/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in `to_a'
	from ~/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in `block in execute'
	from ~/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:95:in `prepare'
	from ~/.rvm/gems/ruby-2.2.2/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in `execute'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/adapters/sqlite.rb:187:in `block (2 levels) in _execute'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/database/logging.rb:33:in `log_yield'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/adapters/sqlite.rb:187:in `block in _execute'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/database/connecting.rb:249:in `block in synchronize'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:99:in `hold'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/database/connecting.rb:249:in `synchronize'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/adapters/sqlite.rb:178:in `_execute'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/adapters/sqlite.rb:149:in `execute_insert'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/dataset/actions.rb:966:in `execute_insert'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/dataset/actions.rb:336:in `insert'
	from ./threading.rb:14:in `block (4 levels) in <main>'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/database/transactions.rb:134:in `_transaction'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/database/transactions.rb:108:in `block in transaction'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/database/connecting.rb:249:in `block in synchronize'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/database/connecting.rb:249:in `synchronize'
	from ~/.rvm/gems/ruby-2.2.2/gems/sequel-4.27.0/lib/sequel/database/transactions.rb:97:in `transaction'
	from ./threading.rb:13:in `block (3 levels) in <main>'
```

@pcarranza: I don't think we should have issues with 10,000 gems during import, it's more about concurrent writes (though size of the dataset seems to help trigger the issue)... so multiple pushes happening at the same time, or maybe someone adding a user authentication while someone else is pushing a gem (come to think of it... that might be problematic with SQLite, considering that is a multi-process scenario, but it is probably such a slim chance to cause a problem, so maybe better to ignore that case). In my original project, we were dealing with maybe a dozen things or so happening around the same time. Earlier in the project, it wasn't happening, only once we had a larger dataset.

**Comment by segiddins** [comment]
Sqlite should pretty much never be used in multiprocess scenarios.

**Comment by smellsblue** [comment]
@segiddins the above script I wrote is multithreaded though, not multiprocess (and Gemstash is multithreaded too... but you could run actions while the server is running that touch the database... we could deal with that by blocking those actions if the server is running and SQLite is in use, though)

**Comment by pcarranza** [comment]
Right, that is really interesting. My take is that SQLite will basically deadlock in a heavy concurrent write scenario. The *good part* is that it will probably survive a heavy write scenario without corruption.

The only situation where I can imagine this scenario is by having a service that is used by a lot of clients that are writing a lot; or when importing those 10k gems while trying to write something or authorise a token.

The former case should be handled with a more beefy SQL server implementation (postgres, mysql, whatever), the later case, even if we insisting in using SQLite (because I assume that later on the use is going to be mostly reads: way more pulling than pushing and we do not want to spend maintaining a service) we could just handle with an exponential backoff retry.

I can see the challenge from the engineering perspective as it is always fun to scale things that should not be capable of doing it (by manually managing synchronisation in this particular case). I just wonder if it just makes sense to let the user know that he needs an infrastructure that matches the kind of use that he is going to do: SQLite for simple tasks with low concurrency, a real service for a real use where a lot of users will be hammering the service. And then just let the service manage the load.

For what is worth, probably the size of the dataset matters because the SQLite will need to load the indexes from the file to then insert the new value and write it back, and while doing this it is basically locking the whole table, which is going to be worse as the dataset grows.
This is usually handled gracefully by services because the indexes are in memory all the time... until you hit the point where the database needs to swap out the index, in which case you start seeing a degraded database, and it is not fun. Or is it?

**Comment by indirect** [comment]
Okay, I think we've gotten a little bit off track here. Let me see if I can summarize and address each issue in this ticket separately:

Issue 1: Writes need to be thread-safe, e.g. Puma using more than one thread to serve requests should not possibly corrupt the database.
Issue 2: Trying to write from two threads at exactly the same time raises an `SQLite3::BusyException`.
Issue 3: SQLite3 may not be suitable for large-scale deployments of gemstash.

Issue 1 is [already solved by SQLite3 itself](https://www.sqlite.org/threadsafe.html). It's not possible to corrupt the database by using the same connection from multiple threads.

Issue 2 is a symptom of SQLite's reduced concurrency support, and can be fixed by simply ensuring that writes happen one at a time. SQLite will do this automatically if you [increase the busy timeout](http://stackoverflow.com/questions/78801/sqlite3busyexception) so that conflicting writes simply wait for their turn rather than raising right away. If we want to do it ourselves, we can add a mutex around write operations so that only execute one write operation a time.

Issue 3 is unclear to me—even a very large gemstash is unlikely to have multiple, critical simultaneous database write operations. But let me be extremely clear: no deadlocks are happening, and it should not even be possible to get this codebase into a state where it deadlocks.

The implication of issue 3 is that it is somehow possible to "scale up" gemstash by switching it from sqlite3 to postgres. However, gemstash is an extremely poor candidate for scaling via adding more web servers that share a database because it depends on the filesystem as well. If you're using gemstash, and you have so many users writing so many gems that sqlite3 can't save them all, you will need to scale your filesystem—you can't just switch to postgres and say the problem's fixed.

Sorry for the novella. *tl;dr*: sqlite3 handles concurrency without danger, and we can prevent errors while using it with a tiny amount of work. there is a limit to how many gems we can save per second, but that limit is based on writing multi-megabyte .gem files to the filesystem, not on any sqlite3 limits.

**Comment by smellsblue** [comment]
Thanks for the analysis @indirect!

I think it's also worth noting that (assuming **not NFS**) [SQLite supports multi-process access](https://www.sqlite.org/faq.html#q5). This means that for the ultra rare case of adding a gem at the same time as adding a new authorization key, SQLite will be fine.

Also, it seems Sequel already uses a [5 second timeout by default](http://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html#label-sqlite).

One more thing, I tweaked my script to have `max_connections: 1` and the busy error completely goes away.

Based on all this info, I'm inclined to say we should have `max_connections: 1` when SQLite is in use. There doesn't seem to be a significant speed problem with that (it actually seemed to be faster on heavy writes), and our database usage is so light that I doubt this would be a problem anyways. This would mean no need for locks, so no chance for deadlocks.

We could also go a `max_connections: 1` write only connection used for any inserts or updates, and a regular connection pool for reads... for non-SQLite DB, the 2 would just be references to the same thing. I don't know if the busy issue would crop up between write and read uses, but it sounded like no.

**Comment by indirect** [comment]
Since even 30 or 60 second timeouts can't provide a guarantee against busy exceptions, I think that only allowing 1 connection seems fine.

**Comment by pcarranza** [comment]
:+1:
