### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by smellsblue** [bundler/gemstash#7]
Add proper logging.

My thoughts for requirements:
* It should default the log to ~/.gemstash/server.log (or something like that)
* The log should have a limit by default, so we don't silently create a multi-hundred megabyte log... perhaps like 10MB or 50 or so by default?
* Utilize some existing logger so we can do debug/info/warn/error
* Look into what Puma logging does

**Comment by pcarranza** [comment]
Looks like we need to provide a sane logging configuration using: http://www.rubydoc.info/gems/logging/Logging/Appenders/RollingFile

Will investigate later

**Comment by pcarranza** [comment]
Done done done.

Logging is such a mess, everything expects to just stdout/stderr.

Now we have only one file, the only issue left is that we are logging with at least 3 formatters, depending on where the logline comes from.

In while (once I forget a bit about logging) I will make an effort for setting up some way of normalizing the formatters, I have an idea how, just didn't wanted to continue that path since we have something that works for now.
