### ISSUE TITLE
Explore not updating index unless explicitly calling `bundle update`

### ISSUE THREAD

**Issue by smellsblue** [bundler/gemstash#73]
Explore the possibility of not updating the index unless `bundle update` is called (or perhaps if the index is over a certain age, like a month or 2 months or whatever). This means, if you create a bunch of rails apps (or otherwise reuse a common set of gems frequently), you won't refresh the index unless you explicitly want to `bundle update`, which saves you in bundling time.

I ran a test against `rails 4.2.5` on a local gemstash server will the necessary gems cached versus bundling against rubygems.org directly. **54.471s** vs **1m41.089s**, then I tried pre-installing nokogiri (since the native building was taking more time than any other gem), and it resulted in **11.160s** vs **32.879s**.

This might be difficult or impossible to implement without causing potential failures when bundling... for example, if you add a requirement for a gem not yet fetched, then this might cause bundling to fail when it shouldn't, so this needs to be carefully thought out.

**Comment by indirect** [comment]
The new index is designed for minimal/partial updates. For example, if no new gems have been released since the last `install`, the only request will be `GET /versions`, the response will be `304 Not Modified`, and the install will proceed.

If new gems have been released, but they are not currently being installed, the response will be `209 Partial Content`, and the response body will contain just the one line per gem that has been released, and then installing will continue.

If new gems have been released, and they are being installed as part of the `install`, then one additional request will be made per gem name. The requests are made in parallel, with up to (I think) 10 requests pending at once. As soon as one response per updated gem that is being installed has come back, installation will continue.

In practice, this means many installs after the first will only make 1 request, and almost all will only make a few, in the 4-10 range. It's... quite fast.

To directly address not updating the index for `install`, we don't always fetch the index—if we can avoid fetching it, we do. But in development mode, people want to be able to change their Gemfile and run `install` to add gems or change versions, which means we often need to run the resolver... which means updating the index.

**Comment by smellsblue** [comment]
This is probably unnecessary then, and anyways might cause more confusion than it's worth. Closing.
