### ISSUE TITLE
Do we have a plan to support S3 being the gem store?

### ISSUE THREAD

**Issue by taoza** [bundler/gemstash#85]
Maybe having gems stored in S3 as the source of truth and cache locally for performance benefit?

**Comment by pcarranza** [comment]
In a way we are already doing something like this because rubygems are stored/cached in fastly.

I see little value in adding complexity to gemstash to store things in S3 when the scope of the project is to work as a transparent proxy for the gems so you don't need to download them again.

@smellsblue any opinion on this?

**Comment by taoza** [comment]
@pcarranza Would you see more value of having S3 as the persistent private gem storage? I'm also interested to know what's on Gemstash's roadmap for supporting private gems. @smellsblue mentioned the possibility of adding permission control over fetch for the same API key (https://github.com/bundler/gemstash/issues/24#issuecomment-195382240), which I guess is a great feature to have. Or I'm just getting it wrong, since the focus of the project is on the transparent proxy instead.

**Comment by smellsblue** [comment]
I think the purpose of Gemstash is split pretty evenly on caching upstream gems and storing private gems. I think @pcarranza is right that S3 for caching the upstream gems probably doesn't make sense. However, it sounds like your intention is more for private gem storage, and I think that would make a lot of sense.

I feel like it might be more appropriate as a plugin though. I have [a branch](https://github.com/bundler/gemstash/tree/plugins) where I started exploring how plugins might work. If you'd like to take a stab at creating such a plugin, feel free to create pull requests to that branch for anything you might need. We can also add documentation to Gemstash for how to set up the plugin... perhaps we could even have a whole page on what plugins we know are available and what they provide.

**Comment by pcarranza** [comment]
@smellsblue Even for storing those gems, does this mean that instead of keeping these private gems, they would be pushed to S3 instead of the local storage? Both? How does the feature look like?

I agree I do see this better as a plugin, I just would like to understand what the feature looks like completely.

**Comment by taoza** [comment]
@pcarranza @smellsblue One example that I'm looking at is the S3 plugin for Geminabox: https://github.com/bkon/geminabox-s3-store/blob/master/lib/geminabox/store/s3.rb

Looks like it treats S3 bucket as the source of truth for gem files and local file store as the cache.

**Comment by pcarranza** [comment]
@taoza I'm closing this in favor of https://github.com/bundler/gemstash/issues/107
